"""init

Revision ID: 993788023de7
Revises:
Create Date: 2025-03-16 11:55:54.410958

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision: str = "993788023de7"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("is_first_login", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "goals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM(
                "ACTIVE", "ACHIEVED", name="statusenum", create_type=False
            ),
            nullable=False,
        ),
        sa.Column(
            "due_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_goals_description"), "goals", ["description"], unique=False
    )
    op.create_index(op.f("ix_goals_id"), "goals", ["id"], unique=False)
    op.create_index(op.f("ix_goals_name"), "goals", ["name"], unique=False)
    op.create_index(
        op.f("ix_goals_user_id"), "goals", ["user_id"], unique=False
    )
    op.create_table(
        "profiles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("firstname", sa.String(), nullable=True),
        sa.Column("lastname", sa.String(), nullable=True),
        sa.Column("bio", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "motivations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("quote", sa.String(length=500), nullable=True),
        sa.Column("link", sqlalchemy_utils.types.url.URLType(), nullable=True),
        sa.Column("goal_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["goal_id"], ["goals.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_motivations_goal_id"), "motivations", ["goal_id"], unique=False
    )
    op.create_index(
        op.f("ix_motivations_id"), "motivations", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_motivations_link"), "motivations", ["link"], unique=False
    )
    op.create_index(
        op.f("ix_motivations_quote"), "motivations", ["quote"], unique=False
    )
    sa.Enum("ACTIVE", "COMPLETED", name="status").drop(op.get_bind())
    op.sync_enum_values(
        enum_schema="public",
        enum_name="statusenum",
        new_values=["ACTIVE", "ACHIEVED"],
        affected_columns=[
            TableReference(
                table_schema="public", table_name="goals", column_name="status"
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="statusenum",
        new_values=["active", "achieved"],
        affected_columns=[
            TableReference(
                table_schema="public", table_name="goals", column_name="status"
            )
        ],
        enum_values_to_rename=[],
    )
    sa.Enum("ACTIVE", "COMPLETED", name="status").create(op.get_bind())
    op.drop_index(op.f("ix_motivations_quote"), table_name="motivations")
    op.drop_index(op.f("ix_motivations_link"), table_name="motivations")
    op.drop_index(op.f("ix_motivations_id"), table_name="motivations")
    op.drop_index(op.f("ix_motivations_goal_id"), table_name="motivations")
    op.drop_table("motivations")
    op.drop_table("profiles")
    op.drop_index(op.f("ix_goals_user_id"), table_name="goals")
    op.drop_index(op.f("ix_goals_name"), table_name="goals")
    op.drop_index(op.f("ix_goals_id"), table_name="goals")
    op.drop_index(op.f("ix_goals_description"), table_name="goals")
    op.drop_table("goals")
    op.drop_table("users")
    # ### end Alembic commands ###
