"""init

Revision ID: c70c6b83deca
Revises:
Create Date: 2025-03-16 16:43:17.458934

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = "c70c6b83deca"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("is_first_login", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "goals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "ACHIEVED", name="status"),
            nullable=False,
        ),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_goals_description"), "goals", ["description"], unique=False
    )
    op.create_index(op.f("ix_goals_name"), "goals", ["name"], unique=False)
    op.create_index(
        op.f("ix_goals_user_id"), "goals", ["user_id"], unique=False
    )
    op.create_table(
        "profiles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("firstname", sa.String(), nullable=True),
        sa.Column("lastname", sa.String(), nullable=True),
        sa.Column("bio", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "motivations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("quote", sa.String(length=500), nullable=True),
        sa.Column("link", sqlalchemy_utils.types.url.URLType(), nullable=True),
        sa.Column("goal_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["goal_id"], ["goals.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_motivations_goal_id"), "motivations", ["goal_id"], unique=False
    )
    op.create_index(
        op.f("ix_motivations_id"), "motivations", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_motivations_link"), "motivations", ["link"], unique=False
    )
    op.create_index(
        op.f("ix_motivations_quote"), "motivations", ["quote"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_motivations_quote"), table_name="motivations")
    op.drop_index(op.f("ix_motivations_link"), table_name="motivations")
    op.drop_index(op.f("ix_motivations_id"), table_name="motivations")
    op.drop_index(op.f("ix_motivations_goal_id"), table_name="motivations")
    op.drop_table("motivations")
    op.drop_table("profiles")
    op.drop_index(op.f("ix_goals_user_id"), table_name="goals")
    op.drop_index(op.f("ix_goals_name"), table_name="goals")
    op.drop_index(op.f("ix_goals_description"), table_name="goals")
    op.drop_table("goals")
    op.drop_table("users")
    # ### end Alembic commands ###
