"""unique is added 

Revision ID: d4fe4405e8dc
Revises: d96510db8fd2
Create Date: 2025-04-09 18:53:40.669173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4fe4405e8dc'
down_revision: Union[str, None] = 'd96510db8fd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_motivations_link', table_name='motivations')
    op.create_index(op.f('ix_motivations_link'), 'motivations', ['link'], unique=True)
    op.drop_index('ix_motivations_quote', table_name='motivations')
    op.create_index(op.f('ix_motivations_quote'), 'motivations', ['quote'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_motivations_quote'), table_name='motivations')
    op.create_index('ix_motivations_quote', 'motivations', ['quote'], unique=False)
    op.drop_index(op.f('ix_motivations_link'), table_name='motivations')
    op.create_index('ix_motivations_link', 'motivations', ['link'], unique=False)
    # ### end Alembic commands ###
