"""cover image is added

Revision ID: d96510db8fd2
Revises: c70c6b83deca
Create Date: 2025-03-18 10:36:05.958699

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = "d96510db8fd2"
down_revision: Union[str, None] = "c70c6b83deca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "goals",
        sa.Column(
            "cover_image", sqlalchemy_utils.types.url.URLType(), nullable=False
        ),
    )
    op.create_index(
        op.f("ix_goals_cover_image"), "goals", ["cover_image"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_goals_cover_image"), table_name="goals")
    op.drop_column("goals", "cover_image")
    # ### end Alembic commands ###
